bluetooth: add missing CNSS2 dependency drivers/built-in.o: In function `enable_extldo': drivers/bluetooth/bluetooth-power.c:306: undefined reference to `cnss_get_platform_cap' drivers/bluetooth/bluetooth-power.c:306:(.text+0x50b378): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `cnss_get_platform_cap'